# Generated by Django 3.0.3 on 2020-03-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_auto_20200303_1522'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['nickname'], name='nickname'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='index_',
        ),
    ]
