# Generated by Django 3.0.3 on 2020-03-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_auto_20200303_1537'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['nickname', 'openid'], name='index__nicknam_7130b0_idx'),
        ),
    ]
